phase-01
Star-Academy/Summer1401-FE-Team02 pull request #1
Opened 2022-07-19 05:54 UTC by Negarnbkhti42

design of landing page

2022-07-20 10:07 UTC, sabaebrahimi requested changes

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/app-routing.module.ts
> +    // {path: '**', component: NotFoundComponent},
کد کامنت شده نداشته باشید

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/footer/footer.component.html
> +            <a href="https://github.com/Star-Academy/Summer1401-FE-Team02"><i class="fa-brands fa-github"></i></a>
<div style="direction: rtl">
بد نیست که لینک ها و مقادیر constant رو داخل فایل ts تون بذارید
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/footer/footer.component.ts
> +  constructor() { }
<div style="direction: rtl">
اگر از ng on init و constructor استفاده نمی کنید پاک شن
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/header/components/search-box/search-box.component.scss
> +        min-width: 270px;
<div style="direction: rtl">
از px استفاده نکنید. 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/header/components/search-box/search-box.component.scss
> +    background-color: #464646;
<div style="direction: rtl">
به hsl تغییر بدید که برای مخاطبی که کدتون رو می خونه رنگش قابل تشخیص تر باشه 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/header/header.component.scss
> +    font-size: 1.1em;
<div style="direction: rtl">
best practice اینه که واسه فونت سایز از درصد استفاده کنید. 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/header/header.component.scss
> +                    color: #bf254b;
<div style="direction: rtl">
رنگ هایی که چندین بار در کد استفاده شدن رو به صورت متغیر در scss در بیارین و بالای فایلتون تعریفش کنید. 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/post-card/post-card.component.scss
> +        height: 400px;
<div style="direction: rtl">
عدم استفاده از px
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/banner-game-tile/banner-game-tile.component.ts
> +    constructor() {}
اگر استفاده نمی کنید پاک کنید.

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.html
> +<!--<div>-->
کامنت پاک بشه

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +    font-size: 2vw;
<div style="direction: rtl">
از vw برای فونت استفاده نکنین 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +interface Ibanner {
<div style="direction: rtl">
IBanner
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +    "Image-address": string,
<div style="direction: rtl">
چرا اطراف Image-address دابل کوت؟ همچنین توی ts، باید camel case تعریف کنیم. 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/first-banner.component.scss
> +    //flex: 1;
comment

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/first-banner.component.ts
> +  constructor() { }
اضافه پاک شه

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/landing-page.component.html
> +            <app-post-card></app-post-card>
<div style="direction: rtl">
چرا ngFor نه؟
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/pages/landing-page/landing-page.component.ts
> +  constructor() { }
پاک شه

2022-07-20 10:07 UTC, sabaebrahimi commented on src/styles.scss
> +    padding: 5px 10px;
<div style="direction: rtl">
استفاده از px رو کم کنین 
</div>

2022-07-20 10:07 UTC, sabaebrahimi commented on src/app/components/footer/footer.component.scss
> +    background-color: #000;
<div style="direction: rtl">
رنگ های سفید و سیاه کدتون رو، به جای #000, #fff، همون black , white بذارید. کد خوانا تر میشه 
</div>

2022-07-20 11:57 UTC, sabaebrahimi approved these changes, later dismissed

2022-07-20 12:33 UTC, BijanEisapour requested changes

2022-07-20 12:33 UTC, BijanEisapour commented on README.md
> +To get more help on the Angular CLI use `ng help` or go check out the [Angular CLI Overview and Command Reference](https://angular.io/cli) page.
قابل قبول نیست
فارسی باشه
اسم سایت
توضیح کامل در مورد پروژه و کارهایی که انجام میده
توضیح در مورد فیچرهای فعلی و فیچرهایی که در آینده میخواید اضافه کنید 
مشخصات توسعه دهندگان 
لینک به CONTRIBUTING.md 
توضیح در مورد

2022-07-20 12:33 UTC, BijanEisapour commented on angular.json
> +                        "styles": ["src/styles.scss", "src/assets/fonts/fontawesome-pro-6.1.1-web/css/all.min.css"],
همیشه اول فایل کتابخونه‌ها رو بذارید که اگه تو کد خودتون ازشون استفاده کردید مشکلی پیش نیاد

2022-07-20 12:33 UTC, BijanEisapour commented on angular.json
> +                        "styles": ["src/styles.scss"],
کو؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/app.component.ts
> +    public title: string = 'game-up';
؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.ts
> +    public gitLink: string = 'https://github.com/Star-Academy/Summer1401-FE-Team02';
چرا متغیره؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +            <a href="#"><i class="fa-brands fa-twitter"></i></a>
وقتی ندارید چرا گذاشتید؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +    <div class="footer__container">
اضافیه

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +            @ تمامی حقوق این سایت متعلق به گروه ۲ فرانت‌اند کارآموزی تابستان ۱۴۰۱ شرکت کد‌استار است.
@ ?

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        a {
چرا کلاس ندادید بهش؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +    width: 100%;
وقتی display: block باشه، خودش width: 100% داره 
پاک شه

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +    color: rgb(162, 162, 162);
hsl

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +    background-color: black;
hsl
دیگه نمیگم
بقیه جاها رو خودتون درست کنید

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +    padding: 2em 1.5em 1em;
آیا واقعاً میخوایم با توجه به فونت، این فاصله کم و زیاد بشه؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        width: 100%;
پاک
دیگه نمیگم

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        gap: 0.625em;
قابل قبول نیست 
همیشه از rem استفاده کنید مگر جایی که واقعاً احتیاج به em باشه 
دیگه نمیگم

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/footer/footer.module.ts
> +export class FooterModule { }
prettier

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.html
> +    <input class="searchbox__input" type="text" placeholder="جست‌وجو" [value]="value" />
type search

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +    background-color:  	hsl(0, 0%, 27%);
prettier

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +        min-width: 16.875em;
فونت سایز html رو بذارید 62.5% که انقد عددهای عجیب غریب نیاز نباشه استفاده کنید

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/header/header.component.scss
> +$red-theme: hsl(345, 68%, 45%);
قابل قبول نیست 
از متغیر css استفاده بشه مگر اینکه مجبور باشید از sass استفاده کنید

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.html
> +<div class="card__container">
اشتباهه 
بالاترین المان نباید از دو بخش تشکیل شده باشه

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.scss
> +        transition: all 0.3s ease-out;
فقط transform و opacity

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.scss
> +        right: 0;
inset-block-start
inset-inline-start

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.scss
> +        -webkit-line-clamp: 1;
از vendorها استفاده نکنید

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.scss
> +        display: -webkit-box;
نکنید
دیگه نمیگم

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/models/Games.ts
> +export const games: Game[] = [
چرا تو پوشه models ئه؟
باید تو data باشه

از طرفی اسمش رو GAMES بذارید که مشخص باشه یه چیز ثابته

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/models/Games.ts
> +        price: 10000,
10_000

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/models/Games.ts
> +        price: 25000,
25_000
دیگه نمیگم

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +.slideshow {
prettier

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +        float: left;
قابل قبول نیست

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +    height: 7vh;
rem

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +    'Image-address': string;
اسم بهتر 
یه چیز تک کلمه‌ای بذارید که راحت بشه استفاده کرد

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +    public banners: Ibanner[] = [
پوشه data

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.html
> +<app-header></app-header>
پایینش enter بخوره

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.html
> +<app-footer></app-footer>
بالاش enter بخوره

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.html
> +                [poster]="game.poster"
خب چرا game رو مستقیم پاس نمیدید جای این همه input ؟

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.scss
> +$spacing: 4rem;
x

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.scss
> +    &--header {
^

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.scss
> +      &::after {
^

2022-07-20 12:33 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.scss
> +  font-size: xx-large;
نه

2022-07-20 16:51 UTC, Negarnbkhti42 commented on src/app/components/post-card/post-card.component.scss
> +        -webkit-line-clamp: 1;
سلام. استفاده از این پراپرتی ها برای ایجاد محدودیت متن نمایشی کارت ها و overflow نشدن هست. راسیتش من راهکار دیگه‌ای برای این مساله نمیشناسم

2022-07-24 06:49 UTC, dorrin-sot commented on src/app/components/header/header.component.scss
> +                    transition: height 0.1s ease-in;
از transition: height نمیتونیم استفاده کنیم. تو داک Animation یه تکنیک FLIP هست که با typescript ه

2022-07-24 06:49 UTC, dorrin-sot commented on src/app/pages/landing-page/landing-page.component.scss
> +        top: 100%;
از logical propertyها برای top left right bottom و paddingها استفاده کنید

2022-07-24 06:49 UTC, dorrin-sot commented on src/app/components/footer/footer.component.scss
> +    padding: 10px 15px;
برای padding از px استفاده نکنید

2022-07-24 07:19 UTC, dorrin-sot approved these changes

2022-07-24 07:55 UTC, dibaaamir requested changes

2022-07-24 07:55 UTC, dibaaamir commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +  .banner-description {
پشت نوشته های توضیحات بازی ها یه بک گراند بزارید چون زیاد معلوم نیستن توی تصویرا

2022-07-24 07:55 UTC, dibaaamir commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +    public ngAfterViewInit(): void {
ایمپلیمنت بشه

2022-07-24 07:55 UTC, dibaaamir commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +    public ngOnDestroy(): void {
ایمپلیمنت بشه

2022-07-24 07:55 UTC, dibaaamir commented on src/app/components/header/header.component.html
> +                        ><img class="header__logo" src="assets/logos/logo-dark-removebg.png" alt="Game Up"
از فایل svg برای لوگو استفاده کنین

2022-07-24 07:55 UTC, dibaaamir commented on src/app/components/header/header.component.html
> +                <li>
decoration لیست پاک شه. یه نقطه مشکلی توی هدره

2022-07-24 09:43 UTC, dibaaamir approved these changes

2022-07-24 10:11 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.ts
> +    private readonly INTERVAL_DELAY: number = 3000;
<div style="direction=rtl">
همه متغیرهای private رو یه قسمت بذارید، متغیر های public رو هم یه قسمت. 
</div>

2022-07-24 10:11 UTC, sabaebrahimi commented on src/styles.scss
> +.btn {
<div style="direction=rtl">
اگر برای همه باتن ها یک استایل دارید و همه شون از یک الگو پیروی می کنند، می تونید یک کامپوننت باتن بسازید و چیزایی مثل تکست داخلش رو به صورت input بهش پاس بدید
</div>

2022-07-24 11:06 UTC, sabaebrahimi approved these changes

2022-07-24 12:01 UTC, BijanEisapour requested changes
تمام عکس‌ها باید فرمت webp داشته باشن و زیر 100 کیلوبایت باشن

2022-07-24 12:01 UTC, BijanEisapour commented on .eslintrc.json
> +                        "prefix": ["app", "icon", "illustration"],
از اینا استفاده میکنید واقعاً ؟

2022-07-24 12:01 UTC, BijanEisapour commented on CONTRIBUTING.md
> +<div dir="rtl" style="font-family: 'Vazirmatn', sans-serif;">
از این حرکتا تو md نکنید

2022-07-24 12:01 UTC, BijanEisapour commented on README.md
> +<div dir="rtl" style="font-family: 'Vazirmatn', sans-serif;">
نمیگم

2022-07-24 12:01 UTC, BijanEisapour commented on README.md
> +این وبسایت در دوره تابستان ۱۴۰۱
گفتم

2022-07-24 12:01 UTC, BijanEisapour commented on angular.json
> +                        "styles": ["src/styles.scss"],
همچنان میگم کو؟

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/app-routing.module.ts
> +const routes: Routes = [{path: '', pathMatch: 'full', component: LandingPageComponent}];
یا صفحه 404 بذارید یا redirect کنید به landing page

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +        ></a>
چسب

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/header/header.component.html
> +                        ><img class="header__logo" src="assets/logos/logo-dark-removebg.svg" alt="Game Up"
وقتی رو باباش title گذاشتید دیگه نیازی نیس رو خودش بذارید 
حالا اصن کاری ندارم این space داره باباش نداره

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/header/header.component.html
> +                        ><img class="header__logo" src="assets/logos/logo-dark-removebg.svg" alt="Game Up"
چسب

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/header/header.component.html
> +                    <a href="https://star-academy.github.io/Summer1401-FE-Team02/" title="GameUp"
اولاً routerLink
ثانیاً آدرس رو از root پروژه بدید 
یعنی اینجا باید / باشه 
چون ممکنه فردا پس‌فردا بخواید domainتون رو عوض کنید 
پروژه نباید از بین بره

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/header/header.component.scss
> +    padding: 1em 3em;
چرا باید وابسته به فونت سایز المان فعلی باشه؟
تا وقتی واقعاً نیاز نباشه، از em استفاده نکنید

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.scss
> +    box-shadow: hsl(0deg 0% 0% / 45%) 0 3px 7px 2px;
unit

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.scss
> +    border-radius: 10px;
unit
نمیگم

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.ts
> +        title: "Wonder boy: The dragon's trap",
Title Case

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.ts
> +            'به دنبال درمانی برای طلسم خود، شما در یک ماجراجویی به دنبال ابزاری جادویی می‌گردید که میتواند طلسم شما را باطل کند.',
یه جا "می‌گردید" یه جا "میتواند"
همه جا از یه قالب استفاده کنید

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.ts
> +        price: 10000,
10_000

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/data/Banners.ts
> +        alt: 'Aery Vikings',
وقتی caption داره نیازی به alt نیست

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/data/Games.ts
> +        price: 10000,
10_000
نمیگم

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +    // height: 70vh;
x

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.scss
> +        -webkit-text-stroke: 0.007rem hsl(0deg 6% 18%);
از vendor prefix استفاده نکنید

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.scss
> +        padding: 2em 3em;
نمیگم

2022-07-24 12:01 UTC, BijanEisapour commented on src/app/pages/landing-page/landing-page.component.scss
> +                border-radius: 2px;
unit

2022-07-24 12:01 UTC, BijanEisapour commented on src/styles.scss
> +.btn {
کامپوننت شه

2022-07-24 14:37 UTC, BijanEisapour approved these changes
خسته نباشید

2022-07-24 17:52 UTC, merged