Phase 03
Star-Academy/Summer1401-FE-Team02 pull request #3
Opened 2022-08-02 05:26 UTC by Negarnbkhti42

2022-08-02 06:20 UTC, SinaMAmini commented on src/app/pages/auth/auth.component.ts
>      public isLogin: boolean | undefined = true;
بهتره جای undefined که خیلی کلی هست، null باشه

2022-08-02 06:20 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +            this.saveCache(data?.token, true, data?.id);
وقتی داخل if اومده یعنی که data وجود داره و نیازی به علامت سوال(?) نیست...

2022-08-02 06:20 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +            this.saveCache(data?.token, true, data?.id);
همانطور که چند خط بالاتر گفتم ...

2022-08-02 06:20 UTC, SinaMAmini commented on src/app/pages/auth/components/signup-form/signup-form.component.html
> +<p>حساب کاربری دارید؟ <a routerLink="/login">وارد حساب خود شوید</a></p>
به نظرم بهتره که کمی از المان بالایی خود فاصله داشته باشد... خیلی چسبیده به دکمه.

2022-08-02 06:20 UTC, SinaMAmini commented on src/app/components/post-card/post-card.component.html
> +            <p class="card__price">{{ game.price.toLocaleString() }} ریال</p>
بنظرم برای راحتی کاربر بهتره از تومان استفاده بشه...

2022-08-02 06:20 UTC, SinaMAmini commented on src/app/components/footer/footer.component.scss
>              transition: opacity 0.1s ease-in;
به نظرم خیلی سریعه و احساس نمیشه.

2022-08-02 06:27 UTC, Negarnbkhti42 commented on src/app/pages/auth/auth.component.ts
>      public isLogin: boolean | undefined = true;
مساله اینه که تو تابع ngOnInit که داریم مقدارش رو تعیین میکنیم ممکنه undefined بشه و به همین خاطر خطا میخوریم

2022-08-02 09:09 UTC, HessamCheraghi requested changes

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/styles/form.scss
> +        background: none;
اگه میخواید پس زمینه ورودی برداشته بشه بهتره از این استفاده کنید:
```css
    background-color: transparent;
```

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/pages/auth/components/signup-form/signup-form.component.ts
> +    }
این متغیر response ثابت هست ولی از let استفاده کردید

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/pages/auth/components/signup-form/signup-form.component.spec.ts
> +    });
برای sign up تستی ننوشتید؟
چند تا تست دقیق شبیه به login هم اینجا بزارید.

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/pages/auth/components/login-form/login-form.component.ts
> +    }
این رو پایین تر گفتم

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/pages/auth/components/login-form/login-form.component.spec.ts
> +        let passwordField = host.querySelector('[name="password"]') as HTMLInputElement;
اینجا همه متغیر ها ثابت هستند و نیازی به تغییر ندارند بهتره از const استفاده کنید

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/pages/auth/components/login-form/login-form.component.spec.ts
> +            let passwordField = host.querySelector('[name="password"]') as HTMLInputElement;
بالاتر گفتم

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/pages/auth/components/login-form/login-form.component.spec.ts
> +        let password = 'pass1';
بالاتر گفتم

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/components/toast/toast.component.ts
این یه دونه اینتر هم پاک کنید

2022-08-02 09:09 UTC, HessamCheraghi commented on src/app/components/toast/toast.component.spec.ts
> +        let type: string = ToastType.INFO;
این ها هم از `const` استفاده کنید

2022-08-02 10:29 UTC, SinaMAmini approved these changes

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/components/footer/footer.component.spec.ts
> +        const copyright_text = host.querySelector('.footer__copyright')!.textContent;
زبان ts، cammel case است

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/components/header/header.component.html
> +                <a routerLink="#" title="سبد خرید"><i class="fa-solid fa-basket-shopping"></i></a>
تو فازهای بعدی قرار نیست سبد خرید رو داشته باشیم. شاید گذاشتن اش دیگه ضروری نباشه

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/components/toast/toast.component.spec.ts
> +        let message: string = 'message';
const

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/components/toast/toast.component.spec.ts
> +    const testtoastMessage = (message: string): void => {
testToastMessage

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/pages/auth/components/signup-form/signup-form.component.html
> +    <section>
از اونجایی که همه این قسمت ها از یک پترن تکراری استفاده می کنن، برای جلوگیری از کد تکراری می تونید این قسمت section رو داخل یک کامپوننت دیگه ببرید.

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.spec.ts
> +        let nextButton = host.querySelector('#nextButton');
const

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/services/auth.service.ts
> +        await this.saveCache(this.token, !!data, data?.id ?? null);
این رو واسه undefined گذاشتید؟ اگر نه که گذاشتنش پوینتلسه

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/services/toast.service.spec.ts
> +    it('tests show', () => {
در صورت null بودن show چی؟

2022-08-02 11:04 UTC, sabaebrahimi commented on src/app/mocks/fetch.mock.ts
> +    public async fetch(url: RequestInfo, init?: RequestInit): Promise<Response> {
به جای init.body و init.method در چند جای کد می تونید بذارید: 
const {body, method} = JSON.parse(init)

2022-08-02 11:15 UTC, HessamCheraghi approved these changes

2022-08-02 11:22 UTC, Negarnbkhti42 commented on src/app/mocks/fetch.mock.ts
> +    public async fetch(url: RequestInfo, init?: RequestInit): Promise<Response> {
ظاهرا کست کردن init به استرینگ برای استفاده در JSON.parse باعث خطا و فیل شدن تستا میشه

2022-08-02 11:27 UTC, Negarnbkhti42 commented on src/app/services/auth.service.ts
> +        await this.saveCache(this.token, !!data, data?.id ?? null);
بله، برای اینکه به جای undefined، null قرار بگیره و علت مقدارش مشخص باشه

2022-08-02 11:30 UTC, Negarnbkhti42 commented on src/app/services/toast.service.spec.ts
> +    it('tests show', () => {
اگر منظورتون تابع show در سرویس هست، ایجاد شدن سرویس و وجود تابع آن در تست قبلی مشخص شده. اگر منظورتون تابع show در کامپوننت تست هست، اون کامپوننت با spyObject در تست ایجاد شده و مساله ای ایجاد نمیشه

2022-08-02 11:37 UTC, AliZoghi reviewed
برای یه سری کامپنتت ها کلا تست نوشته نشده، به عنوان مثال api.service

2022-08-02 11:37 UTC, AliZoghi commented on src/app/components/header/header.component.html
>              <ng-container *ngIf="isLoggedIn; else notLoggedInTemplate">
شرطی که اینجا بکار بردید باید تست شه
برای هدرتون اصلا تست ننوشتید

2022-08-02 11:37 UTC, AliZoghi commented on src/app/components/toast/toast.component.spec.ts
> +        expect(component.isVisible).toBeFalse();
^

2022-08-02 11:37 UTC, AliZoghi commented on src/app/components/toast/toast.component.spec.ts
> +        const toast = host.querySelector('.toast__container');
بهتره همه متغیرا اول تابع تعریف بشه (مگر استثنا باشه که اینجا استثنا نیست)

2022-08-02 11:37 UTC, AliZoghi commented on src/app/components/toast/toast.component.spec.ts
> +        testtoast(message, type);
اسمایی که انتخاب کردید چرا کامل به صورت camelCase نیست؟
میتونست testToast باشه

2022-08-02 11:37 UTC, AliZoghi commented on src/app/components/toast/toast.component.spec.ts
> +        testtoastMessage(message);
نمیگم

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/components/login-form/login-form.component.ts
> +        response && this.router.navigateByUrl('/');
داخل توابع async از await برای فراخوانی تابع ها استفاده کنید
به این شکل: 
response && (await this.router.navigateByUrl('/'))

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/components/login-form/login-form.component.spec.ts
> +        const usernameField = host.querySelector('[name="username"]') as HTMLInputElement;
به جای انتخاب کردن همه input ها میتونید از توابع loop جاوا اسکریپت استفاده کنید.
اینجا دو خط کد زده شده، ولی وقتی تعداد input ها بالا بره نوشتن همش اذیت کننده میشه

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/components/login-form/login-form.component.spec.ts
> +            const usernameField = host.querySelector('[name="username"]') as HTMLInputElement;
اینجا هم میتونید از loop  استفاده کنید.

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/components/signup-form/signup-form.component.spec.ts
> +        const firstnameField = host.querySelector('[name="firstname"]') as HTMLInputElement;
دیگه نمیگم، هرجا که لازم بود اصلاح بشه

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/components/login-form/login-form.component.ts
> +    public async submitForm(): Promise<void> {
برای توابع فرم تست نوشته نشده

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/auth.component.ts
>      public constructor(private router: Router, private route: ActivatedRoute, private authService: AuthService) {}
داخل این کامپننت جایی از authService استفاده نشده، لازم نیست فراخوانیش کنید.

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/auth.component.html
> +        <ng-container *ngIf="isLogin; else signupForm">
وقتی از ngIf استفاده میکنید بهتره یه تست هم براش نوشته بشه و رندر گرفته شدن یا نشدنشو تست کنید.

2022-08-02 11:37 UTC, AliZoghi commented on src/app/pages/auth/auth.component.scss
>          border-radius: 2rem;
وقتی از radius های یکسان استفاده کنید به ui سایتتون کمک میکنید که جلوه قشنگ تری داشته باشه
به همین خاطر اگه از این radius جای دیگه ای هم استفاده کردید داخل استایل عمومی با Custom properties تعریفش کنید

2022-08-02 12:09 UTC, ArefHbb reviewed
خیلی عالی بود خسته نباشید

2022-08-02 12:09 UTC, ArefHbb commented on src/app/components/footer/footer.component.spec.ts
> +        const copyright_text = host.querySelector('.footer__copyright')!.textContent;
بهتر نبود از ؟ به جای ! استفاده میکردید؟

2022-08-02 12:09 UTC, ArefHbb commented on src/app/components/header/header.component.html
>              <ng-container *ngIf="isLoggedIn; else notLoggedInTemplate">
وقتی ngif دارید بهتره توی فایل تست تستش کنید

2022-08-02 12:09 UTC, ArefHbb commented on src/app/components/toast/toast.component.spec.ts
> +        const icon = host.querySelector('.toast__container button i');
کلا یه i توی کدتون دارید میتونستید فقط روی اون querySelector بزنید به جای همه اینا

2022-08-02 12:09 UTC, ArefHbb commented on src/app/data/Banners.ts
>              'سفر خود را در یک دنیای شگفت انگیز، هیجان انگیز و نفس گیر انجام دهید و از احساس پرواز در جستجوی Valhalla لذت ببرید. برای نجات وایکینگ ها از سرنوشت خود، یک خط داستانی جالب را در یک دنیای ص
نیم فاصله -> مهارت های

2022-08-02 12:09 UTC, ArefHbb commented on src/app/pages/auth/components/login-form/login-form.component.spec.ts
> +import {ComponentFixture, fakeAsync, TestBed, tick} from '@angular/core/testing';
کلا کامپوننت های login , sign up تست براش کم نوشته شده برای همین ریتینگ تست این فایلا کمه و کلا ریتینگ تست پروژتون را پایین اورده

2022-08-03 10:35 UTC, sabaebrahimi approved these changes

2022-08-03 14:20 UTC, AliZoghi approved these changes

2022-08-04 08:42 UTC, ArefHbb approved these changes

2022-08-06 14:13 UTC, BijanEisapour approved these changes

2022-08-06 14:13 UTC, BijanEisapour commented on .gitignore
> +To-Do.txt
به جای این، یه issue درست کنید که جفتتون راحت بهش دسترسی داشته باشید و بقیه هم بتونن trackش کنن

2022-08-06 14:13 UTC, BijanEisapour commented on .stylelintrc.json
> +        "value-no-vendor-prefix": null,
پاکش کنید کلاً 
هرچند که مخالف این حرکتم

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/header/header.component.html
> +                        <a routerLink="/login" id="login-link">ورود</a>
اگه صرفاً واسه تست میخواید ازش استفاده کنید به جاش data-test-id بذارید 
```html
<a routerLink="/login" data-test-id="login-link">ورود</a>
```

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/header/header.component.spec.ts
> +    let getLogSpy;
اسم خودِ متد رو بذارید که بشه فهمید چی رو دارید spy میکنید 
```ts
let isLoggedInSpy;
```

بعد چرا type واسش نذاشتید؟

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/header/header.component.spec.ts
> +        fixture.whenStable().then(() => {
وقتی نه async دارید نه fakeAsync چرا از whenStable استفاده کردید؟

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/header/header.component.spec.ts
> +        fixture.whenStable().then(() => {
نمیگم

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.html
> +            <p class="card__price">{{ game.price.toLocaleString() }} تومان</p>
از pipe استفاده کنید

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.spec.ts
> +        const tested_game: Game = {
camelCase

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/post-card/post-card.component.spec.ts
> +        const title_container = host.querySelector('.card__title')!;
نمیگم

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/components/toast/toast.component.ts
>          this.interval = setInterval(() => {
از timeout استفاده کنید

2022-08-06 14:13 UTC, BijanEisapour commented on src/app/pages/landing-page/components/first-banner/components/slide-show/slide-show.component.html
> +                </div>
چرا واسه هر اسلاید به طور جدا button گذاشتید؟

2022-08-09 05:08 UTC, merged